version: '3.8'

services:
  server:
    build:
      dockerfile: Dockerfile
      
    container_name: server-train
    ports:
      - "5000:5000"
    env_file: ./.env

  postgres:
    container_name: db-train
    image: postgres:14
    restart: always
    expose:
      - '5436'
    ports:
      - '5436:5432'
    env_file: ./.env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d